[build]
command = "npm run build"
publish = ".next"

[[redirects]]
from = "/webhooks/twitch"
to = "/.netlify/functions/twitch_eventsub"
status = 200

[functions]
node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-nextjs"
